import React from "react";
import { Dimensions, StyleSheet } from "react-native";

const windowHeight = Dimensions.get('window').height;

export const styles: any = StyleSheet.create({
    smallModal:{
        flex: 4,  
        height: windowHeight - 150,
        width: '100%',
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: 30,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        margin: 0,
    },
    offerModalTitel:{
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
        marginTop: 20,
        fontFamily:'Verdana',
    },
    closeIcon:{
        width: 30,
        height: 30,
        position: 'absolute',
        top: 10,
        right: 30,
        zIndex: 2,
    },
    modalContent: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 30,
        padding: 20,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        margin: 0,
    },
    backgroundImage:{
        zIndex: -1,
        resizeMode: 'stretch',
        position: 'absolute',
        width: '100%',
        height: windowHeight-150,
        flex: 1,
        alignSelf: 'stretch',
        borderRadius: 30,
    },
    offerModalContent:{
        height: '100%',
        flex: 1,
    },
    underlay:{
        position: 'absolute',
        width: '400%',
        height: '400%',
        backgroundColor: 'rgba(255,255,255,0.3)',
        borderRadius: 1000,
        left: '-150%',
        marginTop: 250,
        zIndex: 0,
    },
    bikeContainer:{
        position: 'relative',
        height: '100%',
        width: '100%',
        marginTop: 30,
        borderRadius: 10,
        overflow: 'hidden',
    },
    bikeImage:{
        height: '35%',
        width: '100%',
    },
    bikeInfo:{
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '55%',
        backgroundColor: 'rgba(45,156,219,0.2)',
        zIndex: 1,
        padding: 20,
        borderRadius: 50,
        borderWidth: 0.5,
        borderColor: 'white',
    },
    bikeTitel:{
        fontSize: 20,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    bikeCompanyDurationSelection:{
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
        backgroundColor: 'transparent',
    },
    bikePricePerDay:{
        width: 'auto',
        fontSize: 45,
        color: 'black',
        fontFamily: 'Verdana',
    },
    priceBox:{
        width: '45%',
        height: 'auto',
        fontSize: 45,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
        borderWidth: 0.5,
        borderRadius: 20,
        borderColor: 'white',
        backgroundColor: 'rgba(255,255,255,0.5)',
        padding: 5,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
    },
    innerText:{
        fontSize: 15,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
        borderRadius: 20,
        backgroundColor: 'transparent',
    },
    bikePricePerWeek:{
        fontSize: 20,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    bikeDescription:{
        fontSize: 15,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 15,
        marginBottom: 10,
        textDecorationLine: 'underline',
    },
    datePickerContainer:{
        width: '100%',
        height: 150,
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 10,
        padding: 10,
        color: 'black',
    },
    datePicker:{
        width: '100%',
        height: 100,
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 100,
        padding: 10,
    },
    map:{
        width: '100%',
        height: 300,
        backgroundColor: 'rgba(255,255,255,0.5)',
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 10,
    },
    button:{
        width: '100%',
        height: 50,
        backgroundColor: 'rgba(45,156,219,0.8)',
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 60,
        padding: 5,
    },
    buttonText:{
        fontSize: 25,
        color: 'white',
        textAlign: 'center',
        marginTop: 5,
        fontFamily:'Verdana',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      checkbox: {
        width: 30,
        height: 30,
        borderWidth: 2,
        borderColor: 'black',
        marginRight: 10,
        marginTop: 20,
        marginBottom: 20,
      },
      checkboxChecked: {
        backgroundColor: 'transparent',
      },
      price:{
        fontSize: 70,
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 10,
      },
});