import React from "react";
import { Dimensions, StyleSheet } from "react-native";

const windowHeight = Dimensions.get('window').height;

export const styles: any = StyleSheet.create({
    smallModal:{
        flex: 4,  
        height: windowHeight - 150,
        width: '100%',
        backgroundColor: 'rgba(255,255,255,0.95)',
        borderRadius: 30,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        margin: 0,
    },
    offerModalTitel:{
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
        marginTop: 20,
        fontFamily:'Verdana',
    },
    closeIcon:{
        width: 30,
        height: 30,
        position: 'absolute',
        top: 10,
        right: 30,
        zIndex: 2,
    },
    modalContent: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 30,
        padding: 20,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        margin: 0,
    },
    backgroundImage:{
        zIndex: -1,
        resizeMode: 'stretch',
        position: 'absolute',
        width: '100%',
        height: windowHeight-150,
        flex: 1,
        alignSelf: 'stretch',
        borderRadius: 30,
    },
    offerModalContent:{
        height: '100%',
        flex: 1,
    },
    underlay:{
        position: 'absolute',
        width: '400%',
        height: '400%',
        backgroundColor: 'rgba(255,255,255,0.3)',
        borderRadius: 1000,
        left: '-150%',
        marginTop: 250,
        zIndex: 0,
    },
    bikeContainer:{
        position: 'relative',
        height: '100%',
        width: '100%',
        marginTop: 30,
        borderRadius: 10,
        overflow: 'hidden',
    },
    bikeImage:{
        height: '35%',
        width: '100%',
    },
    bikeInfo:{
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '50%',
        backgroundColor: 'rgba(45,156,219,0.2)',
        zIndex: 1,
        padding: 20,
        borderRadius: 50,
        borderWidth: 0.5,
        borderColor: 'white',
    },
    bikeTitel:{
        fontSize: 20,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    bikePricePerDay:{
        fontSize: 15,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    bikePricePerWeek:{
        fontSize: 15,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    bikeDescription:{
        fontSize: 15,
        color: 'black',
        fontFamily: 'Verdana',
        marginTop: 5,
        marginBottom: 10,
    },
    datePickerContainer:{
        width: '100%',
        height: 100,
        backgroundColor: 'rgba(255,255,255,0.5)',
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 10,
        padding: 10,
        borderWidth: 1,
        borderColor: 'black',
    },
    datePicker:{
        width: '100%',
        height: 50,
        backgroundColor: 'rgba(255,255,255,0.5)',
        borderRadius: 10,
        marginTop: 10,
        marginBottom: 10,
        padding: 10,
        borderWidth: 1,
        borderColor: 'black',
    }
});